### ISSUE TITLE
Is there a way to draw text using glFunctions.js?

### ISSUE THREAD

**Issue by Klockowy** [CCBlueX/LiquidBounce-ScriptAPI#15]
if there is, then how to do that? if not, then create function drawText() pls

**Comment by SenkJu** [comment]
Minecraft has a built-in method to draw strings called 'drawString': https://scriptapi.liquidbounce.net/net/minecraft/client/gui/FontRenderer.html

if you want to draw a circle/rectangle, you can use these methods: https://github.com/CCBlueX/LiquidBounce-ScriptAPI/blob/master/lib/glFunctions.js
