### ISSUE TITLE
Function displayAllReleventItems of Creative Tabs has a Typo

### ISSUE THREAD

**Issue by leumasme** [CCBlueX/LiquidBounce-ScriptAPI#26]
https://liquidbounce.net/docs/ScriptAPI/Creating%20Inventory%20Tabs
"this.displayAllReleventItems"
This is a typo, relev*a*nt is how you spell that.
It's also missspelt in the code everywhere
https://github.com/CCBlueX/LiquidBounce/search?q=displayAllReleventItems&unscoped_q=displayAllReleventItems

**Comment by SenkJu** [comment]
https://github.com/CCBlueX/LiquidBounce1.8-Issues/issues/3713
